### ISSUE TITLE
Sweep: fix the app is not start and failed in get data from api

### ISSUE THREAD

**Issue by Muhammad-Rabieh** [Muhammad-Rabieh/cryptoassets#2]
fix : $ ./cryptoassets
2023/08/18 20:13:47 rate.go:217: GetUSDCNYFromYahoo err:code: remote-error, detail: code: remote-error, detail: error response recieved from upstream api
panic: non-positive interval for NewTicker

goroutine 68 [running]:
time.NewTicker(0x0?)
        /usr/lib/go-1.18/src/time/tick.go:24 +0x10f
main.NewWorker({0xcdd160, 0xc0001f5a00}, 0x0?, 0xc272a0)
        /home/muhammad/sources/cryptoassets/worker.go:9 +0x57
created by main.StartFetchAccount
        /home/muhammad/sources/cryptoassets/exchange.go:338 +0x77
ChatGPT
The error message indicates that there is an issue with creating a NewTicker in your code. The error "non-positive interval for NewTicker" suggests that the interval value passed to time.NewTicker is not a positive duration.

To locate and debug the issue, you should inspect the code in the following locations:

rate.go file: Look for the line where GetUSDCNYFromYahoo function is called. It seems there is an error response received from an upstream API. You might want to handle this error properly.

worker.go file: Examine the NewWorker function in this file. Check the arguments passed to time.NewTicker. Ensure that the interval duration you're passing is a positive value.

exchange.go file: Investigate the StartFetchAccount function in this file. Verify the arguments passed to NewWorker and ensure that the interval duration is positive.

By carefully reviewing and debugging these sections of your code, you should be able to identify and address the issue with creating the NewTicker interval. Make sure to handle error cases properly and ensure that all interval values are positive durations.

<details>
<summary>Checklist</summary>

- [X] `exchange.go`
> • Add error handling in the StartFetchAccount function to check if the period duration is zero or negative before calling the NewWorker function. If the period is not a positive duration, log an error message and return from the function.

- [X] `worker.go`
> • In the NewWorker function, add a condition to check if the period duration is zero or negative. If it is, log an error message and return from the function.

- [X] `rate.go`
> • In the GetUSDCNYFromYahoo function, add error handling for the API call. If there's an error, log it and return a default positive duration.

</details>

**Comment by beaquant** [comment]
🆒
